In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as du
from torch.utils.data import IterableDataset

import numpy as np
import sys
import csv
from os import listdir
from tqdm import tqdm

In [2]:
class Price_Dataset(IterableDataset):
	def __init__(self, directory, window_size = 100, start = 0, end = 8):
		super().__init__()

		self.window_size = window_size

		prices = []
		files = listdir(directory)
		csvs = [f'{directory}/{f}' for f in files if f.endswith('csv')][start:end]
		for c in csvs:
			with open(c, 'r') as f:
				lines = list(csv.reader(f))[1:]
				prices.append(np.array([float(l[5]) for l in lines]))
		prices = np.array(prices)
		for i, row in enumerate(prices):
			for j, col in enumerate(row[:-1]):
				prices[i][j] -= prices[i][j+1]

		self.prices = prices
		self.length = int(len(self.prices)*(
			(len(self.prices[0]) - self.window_size-1)+(len(self.prices[0]) - self.window_size-1)//2+
			(len(self.prices[0]) - self.window_size-1)//3+(len(self.prices[0]) - self.window_size-1)//4+
			(len(self.prices[0]) - self.window_size-1)//5))

	def __len__(self):
		return self.length

	def __iter__(self):
		for p in self.prices:
			for k in np.arange(1, 5):
				for offset in range(0, (len(p) - self.window_size-1)//k):
					out = torch.zeros(self.window_size)
					for i in range(self.window_size):
						out[i] = np.sum(p[offset+i*k:offset+(i+1)*k])
					out = out.unsqueeze(1)
					label = np.sum(p[offset+self.window_size*k:offset+(self.window_size+1)*k])
					yield out.squeeze(dim=1), label

In [3]:
# class Transformer_Model(nn.Module):
#     def __init__(self, d_model, in_dim, hidden_dim, out_dim):
#         super().__init__()
#         self.trans = nn.Transformer(d_model=d_model)
#         # self.fc1 = nn.Linear() 
#     def forward(self, x):
#         x = self.trans(x)
#         return x
class FFN(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, out_dim)
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

In [4]:
device = f'cuda:0' if torch.cuda.is_available() else 'cpu'
print(f"using device: {device}")
epochs = 5
learning_rate = 1e-4
batch_size = 20
window_size = 80
# start = 0
# end = 4

train_dataset = Price_Dataset('Kline/filter', window_size=window_size)
train_loader = du.DataLoader(dataset = train_dataset, batch_size = batch_size)

# net = Transformer_Model(window_size, 1, 1, 1)
net = FFN(80, 40, 1)
optimizer = optim.Adam(net.parameters(), lr = learning_rate)

loss_func = nn.CrossEntropyLoss()
a,b = next(iter(train_loader))
net = net.to(device)
net.train()
# net = 3

using device: cuda:0


FFN(
  (fc1): Linear(in_features=80, out_features=40, bias=True)
  (fc2): Linear(in_features=40, out_features=40, bias=True)
  (fc3): Linear(in_features=40, out_features=1, bias=True)
)

In [5]:
for epoch in range(1 , epochs + 1):
    sum_loss = 0
    for batch_idx, (price, label) in enumerate(tqdm(train_loader)):
        price, label = price.to(device), label.to(device)
        print(label)
        optimizer.zero_grad()
        pred = net(price)
        loss = loss_func(pred.type(torch.float), label.type(torch.long))
        loss.backward()
        optimizer.step()
        sum_loss += loss.item()
    print(f'Epoch {epoch}: Train loss: {sum_loss/batch_idx/batch_size:.8f}')

  0%|          | 0/839 [00:00<?, ?it/s]

tensor([-0.0050,  0.0005,  0.0047, -0.0056, -0.0070,  0.0058,  0.0227, -0.0039,
        -0.0019, -0.0067, -0.0070, -0.0382, -0.0031,  0.0040,  0.0022, -0.0250,
         0.0206, -0.0212, -0.0084,  0.0129], device='cuda:0',
       dtype=torch.float64)


  1%|          | 5/839 [00:02<04:32,  3.06it/s]

tensor([-0.0090,  0.0088, -0.0098,  0.0098, -0.0036,  0.0076, -0.0031,  0.0077,
        -0.0061, -0.0083,  0.0051,  0.0050,  0.0007,  0.0117, -0.0063,  0.0241,
        -0.0047, -0.0226, -0.0102,  0.0062], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0090,  0.0160,  0.0076, -0.0036,  0.0323, -0.0158,  0.0076, -0.0150,
        -0.0201, -0.0014,  0.0039, -0.0012, -0.0061,  0.0186, -0.0054, -0.0055,
         0.0025, -0.0027, -0.0036, -0.0136], device='cuda:0',
       dtype=torch.float64)
tensor([ 1.1260e-02,  1.1970e-02, -1.0970e-02, -6.5600e-03,  5.5300e-03,
        -2.2000e-03, -5.0500e-03,  9.4400e-03,  9.2100e-03,  5.8200e-03,
        -4.2500e-03,  2.1800e-03,  5.1300e-03, -8.0200e-03, -1.0800e-03,
         1.1230e-02,  5.0000e-05,  1.2130e-02,  6.6000e-04,  3.4500e-03],
       device='cuda:0', dtype=torch.float64)
tensor([ 0.0043, -0.0141, -0.0047, -0.0063, -0.0053,  0.0014, -0.0037,  0.0057,
        -0.0066, -0.0216,  0.0084,  0.0117, -0.0011,  0.0066, -0.0016, -0.0007,
  

  1%|▏         | 11/839 [00:02<01:46,  7.79it/s]

tensor([-0.0183, -0.0081, -0.0206, -0.0139,  0.0656, -0.0026, -0.0470,  0.0177,
        -0.0204, -0.0242,  0.0043, -0.0262,  0.0335, -0.0076,  0.0037, -0.0011,
         0.0009, -0.0154, -0.0098, -0.0680], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0341, -0.0620,  0.0517, -0.0278, -0.0938,  0.0567, -0.0351,  0.0133,
        -0.0318, -0.0189,  0.0275,  0.0394, -0.0171, -0.0050, -0.0097,  0.0039,
        -0.0078, -0.0105,  0.0330,  0.0345], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0296,  0.0088, -0.0248,  0.0406, -0.0037,  0.0034,  0.0397, -0.0123,
         0.0016,  0.0387, -0.0115, -0.0277, -0.0302, -0.0038,  0.0166, -0.0184,
         0.0060, -0.0125,  0.0078,  0.0158], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0074,  0.0254, -0.0204, -0.0007, -0.0024, -0.0211, -0.0029, -0.0163,
        -0.0366,  0.0236, -0.0016,  0.0159, -0.0073,  0.0171, -0.0170, -0.0282,
         0.0281, -0.0119,  0.0005, -0.1084], device='cuda:0',
       dtype=torch.float64)


  2%|▏         | 19/839 [00:02<00:52, 15.65it/s]

tensor([ 2.1610e-02, -2.2410e-02, -8.9100e-02, -1.0505e-01,  9.8600e-02,
        -4.1810e-02,  8.8780e-02,  1.4295e-01, -2.5150e-02, -7.8280e-02,
         7.0500e-02, -7.1030e-02, -3.7000e-02,  3.8810e-02, -3.7700e-03,
         6.2100e-03, -8.1700e-03,  1.4000e-04, -1.7460e-02,  7.9760e-02],
       device='cuda:0', dtype=torch.float64)
tensor([ 0.0041, -0.0209, -0.0092,  0.0467, -0.0271,  0.0045, -0.0231, -0.0021,
         0.0106, -0.0064,  0.0261,  0.0176, -0.0076,  0.0385,  0.0144,  0.0352,
         0.0026,  0.0368, -0.0639,  0.0156], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0432, -0.0103,  0.0183,  0.0175, -0.0063,  0.0279,  0.0134,  0.0018,
        -0.0242,  0.0012, -0.0022, -0.0082,  0.0111,  0.0073, -0.0106, -0.0128,
         0.0230, -0.0022,  0.0014,  0.0042], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0017, -0.0226,  0.0149, -0.0650,  0.0173, -0.0084, -0.0149,  0.0522,
        -0.0184, -0.0004, -0.0003, -0.0018,  0.0332,  0.0005,  0.0105, -0.0034,
  

  3%|▎         | 27/839 [00:02<00:35, 23.16it/s]

tensor([ 0.0048, -0.0074,  0.0117, -0.0269, -0.0192, -0.1180,  0.0387,  0.0133,
        -0.0065,  0.0334, -0.0117,  0.0158, -0.0027, -0.0061,  0.0087, -0.0172,
        -0.0119,  0.0172, -0.0007,  0.0092], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0097,  0.0045, -0.0223,  0.0002,  0.0047, -0.0033,  0.0036,  0.0090,
        -0.0176, -0.0195,  0.0199, -0.0189,  0.0175,  0.0253,  0.0003,  0.0050,
        -0.0103,  0.0078, -0.0082,  0.0041], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0036,  0.0014, -0.0043,  0.0094,  0.0011, -0.0077, -0.0341,  0.0177,
        -0.0039,  0.0160,  0.0057, -0.0318, -0.0036,  0.0089,  0.0103,  0.0100,
         0.0338, -0.0186,  0.0088, -0.0005], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0045, -0.0034, -0.0015, -0.0016,  0.0133, -0.0106, -0.0268,  0.0146,
        -0.0186,  0.0123, -0.0030,  0.0002, -0.0711,  0.0157,  0.0057, -0.0163,
         0.0211,  0.0554,  0.0090,  0.0024], device='cuda:0',
       dtype=torch.float64)


  4%|▍         | 35/839 [00:03<00:27, 29.02it/s]

tensor([-0.0238,  0.0504, -0.0504,  0.0034,  0.0580,  0.0116, -0.0264, -0.0096,
        -0.0044,  0.0163,  0.0720,  0.0494,  0.0902, -0.1230,  0.0294, -0.0345,
        -0.0262,  0.0139, -0.0253,  0.0522], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0134,  0.0042,  0.0242,  0.0108, -0.0056, -0.0184, -0.0257,  0.0358,
         0.0147, -0.0907, -0.0322, -0.0231,  0.0105, -0.0095, -0.0012, -0.0054,
        -0.0142, -0.0710,  0.0120,  0.0220], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0122,  0.0047,  0.0262, -0.0214, -0.0002, -0.0348, -0.0061,  0.0177,
        -0.0844,  0.0145,  0.0324,  0.0594, -0.0080, -0.0075, -0.0336,  0.0187,
        -0.0248, -0.0039,  0.0042, -0.0128], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0188,  0.0057,  0.0084,  0.0006, -0.0191,  0.0432, -0.0066, -0.0065,
        -0.0112, -0.0140,  0.0200, -0.0183, -0.0144, -0.0133,  0.0298, -0.0213,
         0.0020,  0.0632, -0.0083, -0.0333], device='cuda:0',
       dtype=torch.float64)


  5%|▌         | 43/839 [00:03<00:25, 31.47it/s]

tensor([ 0.0585, -0.0311, -0.0267, -0.0193,  0.1058, -0.0295,  0.0279,  0.1747,
         0.0466,  0.1880, -0.0384, -0.0056,  0.1720, -0.0941, -0.1352, -0.1040,
        -0.0528,  0.0436,  0.0082,  0.0466], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0447, -0.0057,  0.1907,  0.0445, -0.0695,  0.0414,  0.0695, -0.0944,
        -0.0031,  0.0959, -0.0229, -0.0194,  0.0891,  0.1283,  0.0959, -0.0004,
        -0.1445, -0.0554, -0.1135, -0.0014], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0202, -0.0718,  0.0262,  0.0103, -0.0620,  0.1550, -0.1137,  0.0601,
        -0.0529, -0.1241, -0.1043,  0.0082,  0.0597, -0.0044, -0.0610,  0.1258,
        -0.0487, -0.0348,  0.0181,  0.0440], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0195, -0.0179,  0.1039,  0.1076, -0.0837,  0.0015,  0.0305, -0.0371,
         0.0493,  0.0161,  0.0875,  0.0392, -0.0446, -0.0791, -0.1381, -0.0707,
         0.0655, -0.0007,  0.0509,  0.0243], device='cuda:0',
       dtype=torch.float64)


  6%|▌         | 51/839 [00:03<00:23, 33.80it/s]

tensor([ 0.0197,  0.0023,  0.0338,  0.0063,  0.0003,  0.0025,  0.0223, -0.0093,
         0.0259,  0.0301,  0.0242,  0.0465, -0.0070, -0.0351, -0.0264, -0.0165,
        -0.0033,  0.0278,  0.0147, -0.0037], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0200, -0.0856, -0.0509,  0.0188, -0.0017,  0.0235, -0.0644,  0.0311,
        -0.0276,  0.0041, -0.0239,  0.0205,  0.0204, -0.0022,  0.0028,  0.0100,
        -0.0168,  0.0413,  0.0165, -0.0097], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0188, -0.0110, -0.0116, -0.0039, -0.0023,  0.0020, -0.0008, -0.0282,
        -0.0132,  0.0201,  0.0106,  0.0056,  0.0050, -0.0023, -0.0101, -0.0154,
        -0.0113, -0.0011,  0.0080,  0.0045], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0119,  0.0118, -0.0006, -0.0022, -0.0025, -0.0060, -0.0036, -0.0124,
        -0.0579, -0.0442, -0.0162, -0.0099, -0.0174, -0.0011,  0.0174, -0.0150,
        -0.0036,  0.0168, -0.0008, -0.0210], device='cuda:0',
       dtype=torch.float64)


  7%|▋         | 59/839 [00:03<00:22, 34.80it/s]

tensor([ 5.0300e-03, -2.1040e-02, -3.0600e-03, -2.3490e-02, -2.4030e-02,
        -1.9250e-02, -5.2920e-02, -1.3040e-02,  2.1950e-02,  1.4270e-02,
         8.6100e-03,  9.8400e-03,  1.4000e-04, -4.5140e-02, -6.0000e-05,
         1.6160e-02, -1.1470e-02, -1.0794e-01, -9.7540e-02, -2.4750e-02],
       device='cuda:0', dtype=torch.float64)
tensor([-0.0645, -0.0904, -0.0278,  0.0443,  0.0119, -0.0307, -0.0035,  0.0214,
         0.0083,  0.0686,  0.0284,  0.0419,  0.0804, -0.0305, -0.1069,  0.0006,
         0.1085,  0.1266,  0.0162,  0.0135], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0104, -0.1110, -0.0391, -0.0377, -0.0256,  0.0153, -0.0223, -0.0076,
         0.0059, -0.0120, -0.0768, -0.0859,  0.0431,  0.0513,  0.0580, -0.0271,
        -0.1431, -0.1564, -0.0810, -0.0008], device='cuda:0',
       dtype=torch.float64)
tensor([-0.1115, -0.1942, -0.0064,  0.0568,  0.0470,  0.2317,  0.1178, -0.1034,
        -0.0078, -0.0005, -0.1080,  0.0018,  0.0350,  0.0024, -0.0020, -0.0080,
  

  8%|▊         | 67/839 [00:03<00:21, 35.73it/s]

tensor([-0.0013,  0.0208, -0.0125, -0.0137, -0.0480, -0.1902, -0.1577,  0.0156,
        -0.0145, -0.0242,  0.0347, -0.0288, -0.1480, -0.1421, -0.0260, -0.0232,
        -0.0454,  0.1688,  0.2192,  0.0241], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0348, -0.0239, -0.0163, -0.0785, -0.0145,  0.0662,  0.0334,  0.0071,
         0.0058,  0.0156,  0.0551,  0.0258, -0.0112,  0.0398,  0.0085, -0.0155,
         0.0175,  0.0070, -0.0096,  0.0017], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0153,  0.0402,  0.0784,  0.0210, -0.0270,  0.0018, -0.0280,  0.0012,
         0.0401,  0.0183, -0.0244, -0.0411,  0.0002,  0.0434,  0.0715,  0.0162,
        -0.0132, -0.0152, -0.0177, -0.0026], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0043, -0.0152, -0.0461, -0.1372, -0.0793,  0.0520,  0.0068,  0.0269,
         0.0217,  0.0041,  0.0131, -0.0088,  0.0026, -0.0086, -0.0291,  0.0054,
         0.0165,  0.0085, -0.0005, -0.0051], device='cuda:0',
       dtype=torch.float64)


  9%|▉         | 75/839 [00:04<00:21, 36.14it/s]

tensor([-0.0298, -0.0376, -0.0232, -0.0670, -0.0291,  0.0085,  0.0157,  0.0123,
        -0.0373, -0.0047,  0.0012, -0.0295, -0.0682, -0.0767, -0.0312, -0.0428,
        -0.0925, -0.0122, -0.0444, -0.0382], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0699, -0.0650, -0.0722,  0.0348, -0.0536, -0.0374, -0.0231,  0.0480,
         0.0497,  0.0173, -0.0318, -0.0107, -0.0136, -0.0144,  0.0146,  0.0569,
         0.0378,  0.0136, -0.0456,  0.0246], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0121,  0.0403,  0.0394,  0.0308,  0.0290,  0.0281,  0.0288, -0.0004,
        -0.0694, -0.0616, -0.0173, -0.0055,  0.0043, -0.0248,  0.0013,  0.0111,
         0.0163,  0.0339, -0.0023,  0.0044], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0234, -0.0242, -0.0264, -0.0403, -0.0559, -0.0293, -0.0147,  0.0378,
         0.0070,  0.0257, -0.0071, -0.0280, -0.0170, -0.0120,  0.0166, -0.1199,
        -0.0971, -0.1332, -0.0536, -0.1260], device='cuda:0',
       dtype=torch.float64)


 10%|▉         | 83/839 [00:04<00:20, 36.39it/s]

tensor([ 0.0295,  0.0391,  0.0350,  0.0431, -0.0090, -0.0211, -0.0252, -0.0092,
         0.0007,  0.0102,  0.0077, -0.0162, -0.0005,  0.0080,  0.0222,  0.0034,
         0.0040, -0.0201, -0.0094, -0.0727], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0327, -0.0561, -0.0060,  0.0289,  0.0189,  0.0334, -0.0191, -0.0024,
         0.0311,  0.0319,  0.0442,  0.0076,  0.0130,  0.0116,  0.0007,  0.0041,
         0.0234,  0.0473,  0.0402,  0.0436], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0449,  0.0247, -0.0112, -0.1095, -0.0682, -0.0515,  0.0416,  0.0308,
         0.0260,  0.0203,  0.0149, -0.0030,  0.0273,  0.0112,  0.0451,  0.0266,
         0.0317, -0.0053, -0.0051,  0.0075], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0005, -0.0049, -0.0693, -0.1825, -0.2133, -0.1190, -0.0377,  0.0146,
        -0.0185,  0.0003, -0.1423, -0.1766, -0.1396, -0.0518, -0.0428,  0.1430,
         0.1996,  0.2125, -0.0040, -0.0306], device='cuda:0',
       dtype=torch.float64)


 11%|█         | 91/839 [00:04<00:20, 36.62it/s]

tensor([ 0.0062,  0.0028, -0.0407, -0.0241, -0.0975, -0.0287, -0.1487, -0.0647,
        -0.0224, -0.0480,  0.0078, -0.0165, -0.0195, -0.0710, -0.0978, -0.0337,
        -0.0346,  0.1011,  0.0242, -0.0851], device='cuda:0',
       dtype=torch.float64)
tensor([-0.1835, -0.2242, -0.1572, -0.1925, -0.1949, -0.1180, -0.1374,  0.0405,
         0.2885,  0.1648,  0.1283,  0.1100, -0.1040, -0.1158,  0.0013, -0.0730,
         0.0043,  0.0331, -0.0056, -0.0193], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0543,  0.0666,  0.0456,  0.0538,  0.0208, -0.0104,  0.0150,  0.0011,
        -0.0478, -0.0101, -0.0210,  0.0283,  0.0480,  0.0298,  0.0746,  0.0629,
         0.0805,  0.0907,  0.0890,  0.0107], device='cuda:0',
       dtype=torch.float64)
tensor([-0.0089, -0.0546, -0.1017, -0.0196, -0.0177,  0.0191,  0.0574,  0.0525,
         0.0368,  0.0189, -0.0078, -0.0234, -0.0334,  0.0019,  0.0080, -0.0004,
        -0.0051,  0.0068, -0.0026,  0.0094], device='cuda:0',
       dtype=torch.float64)


 11%|█▏        | 95/839 [00:04<00:20, 36.67it/s]

tensor([-0.0086,  0.0079,  0.0087,  0.0057,  0.0419,  0.0937,  0.0612,  0.0514,
         0.0228, -0.0550,  0.0030,  0.0121,  0.0195,  0.0158, -0.0228, -0.0242,
         0.0023,  0.0718,  0.0596,  0.0584], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0009, -0.0309, -0.0178, -0.0134, -0.0178, -0.0418, -0.1523, -0.1254,
        -0.0852, -0.0725,  0.0789,  0.0285,  0.0310,  0.0348, -0.0047,  0.0157,
        -0.0174, -0.0265, -0.0032, -0.0126], device='cuda:0',
       dtype=torch.float64)
tensor([ 0.0139,  0.0161,  0.0034, -0.0182, -0.0272, -0.0129, -0.0207,  0.0052,
         0.0139, -0.0083, -0.0245, -0.0081, -0.0360, -0.0009,  0.0438,  0.0242,
         0.0481,  0.0203,  0.0029, -0.0056], device='cuda:0',
       dtype=torch.float64)
tensor([-6.5300e-03,  2.0000e-04, -6.2400e-03, -2.3800e-03,  2.9000e-03,
         7.6300e-03, -1.5200e-03, -3.1290e-02, -2.2980e-02, -2.7980e-02,
        -4.2200e-03,  3.5600e-02, -1.3890e-02,  2.0000e-01, -1.0400e-01,
        -5.6000e-02, -1.0630e+0

 11%|█▏        | 95/839 [00:05<00:40, 18.24it/s]


RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.